name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - name: Get CPM
        uses: neacsum/configurator@v0.0.11
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Build libraries
        run: cpm -v --proto https -u https://github.com/neacsum/utf8.git -r $HOME utf8
        
      - name: Build and run tests
        shell: cmd
        run: |
          %USERPROFILE%\utf8\build.bat tests

      - name: Save tests result
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: |
            build/exe/x64/debug/utf8_tests.xml
            build/exe/x64/release/utf8_tests.xml

