name: Doxygen GitHub Pages Deploy Action

on: wokflow_dispatch

jobs:
  make_docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4

      - name: Download Doxygen
        uses: engineerd/configurator@v0.0.10
        with:
          name: doxygen.exe
          url: https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.windows.x64.bin.zip
          pathInArchive: doxygen.exe

      - name: Generate Doxygen documentation
        run: doxygen tools/doxygen/Doxyfile